# Site settings
title: Filament Coffee | Speciality Coffee in Edinburgh
email: filamentcoffee@outlook.com
description: "Filament Coffee is a specialty coffee shop in Edinburgh."
baseurl: ""
url: "http://filamentcoffee.com"

# Build settings
markdown: kramdown
permalink: pretty
